version: '3'

services:

  haproxy.service:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - brussels.service
      - home.service
      - london.service
      - paris.service
      - static.service

  authentication.service:
    build:
      context: ./authentication
      dockerfile: Dockerfile

  brussels.service:
    build:
      context: ./brussels
      dockerfile: Dockerfile

  home.service:
    build:
      context: ./home
      dockerfile: Dockerfile

  london.service:
    build:
      context: ./london
      dockerfile: Dockerfile

  paris.service:
    build:
      context: ./paris
      dockerfile: Dockerfile
        
  static.service:
    build:
      context: ./static
      dockerfile: Dockerfile
